services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./conexion_BD.py"
    depends_on:
      - mysql

  mysql:
    build: ./MySQL/
    restart: always
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: 'sql12345'
    ports:
      - '3306:3306'